In [79]:
import pandas as pd

In [80]:
import numpy as np

In [81]:
df=pd.read_csv('compcar_parts_dataframe.csv')

In [82]:
df.head()

   index  make  model  year  part               image
0      0    78      1  2012     1  4d866be9780740.jpg
1      1    78      1  2010     1  adebdf35537df0.jpg
2      2    78      1  2014     1  b621379106f125.jpg
3      3    78      1  2013     1  02dba947d556ab.jpg
4      4    78      1  2012     1  3f9c8be4df00f3.jpg

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11059 entries, 0 to 11058
Data columns (total 6 columns):
index    11059 non-null int64
make     11059 non-null int64
model    11059 non-null int64
year     11059 non-null int64
part     11059 non-null int64
image    11059 non-null object
dtypes: int64(5), object(1)
memory usage: 518.5+ KB

In [89]:
j=df.groupby(['make']).count()

In [91]:
j.sort_values('image', ascending=False)

      index  model  year  part  image
make
73      888    888   888   888    888
78      568    568   568   568    568
81      524    524   524   524    524
111     403    403   403   403    403
39      395    395   395   395    395
77      393    393   393   393    393
157     370    370   370   370    370
102     356    356   356   356    356
140     328    328   328   328    328
54      326    326   326   326    326
118     294    294   294   294    294
162     291    291   291   291    291
122     257    257   257   257    257
158     254    254   254   254    254
97      250    250   250   250    250
152     248    248   248   248    248
149     230    230   230   230    230
75      228    228   228   228    228
95      226    226   226   226    226
159     225    225   225   225    225
100     216    216   216   216    216
38      202    202   202   202    202
28      197    197   197   197    197
105     169    169   169   169    169
53      162    162   162   162    162
142     159    159   159   159    159
114     155    155   155   155    155
131     153    153   153   153    153
108     153    153   153   153    153
76      152    152   152   152    152
...     ...    ...   ...   ...    ...
37       54     54    54    54     54
71       50     50    50    50     50
70       50     50    50    50     50
55       48     48    48    48     48
103      43     43    43    43     43
26       42     42    42    42     42
94       39     39    39    39     39
58       34     34    34    34     34
155      32     32    32    32     32
36       31     31    31    31     31
120      28     28    28    28     28
50       24     24    24    24     24
34       20     20    20    20     20
51       17     17    17    17     17
138      16     16    16    16     16
87       16     16    16    16     16
128      16     16    16    16     16
121      16     16    16    16     16
45       15     15    15    15     15
29       15     15    15    15     15
119      14     14    14    14     14
148      14     14    14    14     14
84       14     14    14    14     14
64       13     13    13    13     13
106      11     11    11    11     11
68        8      8     8     8      8
133       8      8     8     8      8
80        8      8     8     8      8
89        8      8     8     8      8
88        8      8     8     8      8

[75 rows x 5 columns]

In [85]:
#similary do it for other makes
df39 = df[df['make']==39]

In [61]:
df39

       index  make  model  year  part               image
991      991    39   1321  2013     1  ce15b22d78b4eb.jpg
992      992    39   1321  2009     1  7a8495f3d52bc1.jpg
993      993    39   1321  2009     1  a94ebe2a8edc0a.jpg
994      994    39   1321  2009     1  6f16ef3caf634d.jpg
995      995    39   1321  2012     1  d09d6e7adeebcf.jpg
996      996    39   1322  2012     1  cf9fe3c7fba07a.jpg
997      997    39   1322  2012     1  b732abfa70a082.jpg
998      998    39   1322  2010     1  06069fddc8d071.jpg
999      999    39   1322  2012     1  0547d2f03ea530.jpg
1000    1000    39   1322  2010     1  1bb51f4568e1ae.jpg
1001    1001    39   1325  2010     1  54aaa8889f1b85.jpg
1002    1002    39   1325  2012     1  e7b4e39b11f868.jpg
1003    1003    39   1326  2014     1  9f3f8c46ffed5d.jpg
1004    1004    39   1326  2010     1  cfb1f0934a0eee.jpg
1005    1005    39   1326  2014     1  cd0eb55eb472ec.jpg
1006    1006    39   1326  2006     1  83d367572826d5.jpg
1007    1007    39   1327  2012     1  de2b4bed23232d.jpg
1008    1008    39   1327  2012     1  dd511842daa3c4.jpg
1009    1009    39   1328  2010     1  20e99bce05d50a.jpg
1010    1010    39   1328  2013     1  423cab1e19ea08.jpg
1011    1011    39   1328  2010     1  927b2db098f49d.jpg
1012    1012    39   1328  2013     1  336e59c07b05cf.jpg
1013    1013    39   1329  2013     1  526af9f42ab54e.jpg
1014    1014    39   1329  2011     1  a0a1681f187397.jpg
1015    1015    39   1329  2011     1  166fae81b42a16.jpg
1016    1016    39   1329  2014     1  72cb1f637f0c7d.jpg
1017    1017    39   1330  2010     1  2fc1924ca8c262.jpg
1018    1018    39   1330  2011     1  4964c6006790a3.jpg
1019    1019    39   1330  2013     1  edea8c2648ce57.jpg
1020    1020    39   1330  2013     1  5020cb882cbb20.jpg
...      ...   ...    ...   ...   ...                 ...
10639    954    39   1328  2013     8  b7c11578ab767e.jpg
10640    955    39   1328  2010     8  fd5a27acdc7011.jpg
10641    956    39   1329  2011     8  cf76a8f84a2d46.jpg
10642    957    39   1329  2011     8  5cd72b168efdd0.jpg
10643    958    39   1329  2014     8  2c6804d2ebdc5d.jpg
10644    959    39   1329  2013     8  e9a5b68bfb3c05.jpg
10645    960    39   1330  2011     8  22baa178bb711c.jpg
10646    961    39   1330  2013     8  ac4bacc7d57ec7.jpg
10647    962    39   1330  2010     8  f26b208b6e07e6.jpg
10648    963    39   1330  2011     8  fc8ee429c120a9.jpg
10649    964    39   1332  2013     8  59e76b7b321fbc.jpg
10650    965    39   1332  2013     8  696f4beb8ce861.jpg
10651    966    39   1333  2013     8  eebecc524ea838.jpg
10652    967    39   1333  2012     8  b9159664d008ee.jpg
10653    968    39   1335  2013     8  f3b428b630bd41.jpg
10654    969    39   1386  2010     8  5010d388a83743.jpg
10655    970    39   1386  2009     8  e117b8b6a76204.jpg
10656    971    39   1386  2010     8  e820cf5484fbfd.jpg
10657    972    39   1386  2010     8  e49214c41b9489.jpg
10658    973    39   1386  2012     8  b94d642064cafb.jpg
10659    974    39   1386  2013     8  3ae5d87cc52b6c.jpg
10660    975    39   1386  2013     8  b7dfb7abeaa1cb.jpg
10661    976    39   1387  2012     8  045d188881ecc3.jpg
10662    977    39   1387  2012     8  811c09dc24b9f4.jpg
10663    978    39   1389  2011     8  2d20b6e94e016d.jpg
10664    979    39   1389  2011     8  8665242ce523d4.jpg
10665    980    39   1390  2011     8  6d2a6930990f3d.jpg
10666    981    39   1390  2012     8  6fb4f766c68469.jpg
10667    982    39   1390  2012     8  4cb3bb98084046.jpg
10668    983    39   1390  2011     8  28122ed6fa2535.jpg

[395 rows x 6 columns]

In [62]:
a=df39.groupby(['model','year']).count()

In [63]:
a.sort_values('model', ascending=False)

            index  make  part  image
model year
1390  2014      8     8     8      8
      2012      9     9     9      9
      2011     14    14    14     14
1389  2011     16    16    16     16
1387  2012     15    15    15     15
1386  2011      7     7     7      7
      2008      4     4     4      4
      2009     15    15    15     15
      2010     18    18    18     18
      2012     14    14    14     14
      2013     10    10    10     10
1335  2013      8     8     8      8
1333  2013      8     8     8      8
      2012      4     4     4      4
      2011      4     4     4      4
1332  2013     14    14    14     14
      2009      2     2     2      2
1330  2011      9     9     9      9
      2013     12    12    12     12
      2010     10    10    10     10
1329  2013      5     5     5      5
      2011     13    13    13     13
      2014     13    13    13     13
1328  2013     14    14    14     14
      2012      5     5     5      5
      2010     13    13    13     13
1327  2012     14    14    14     14
1326  2010     19    19    19     19
      2014      9     9     9      9
      2006      3     3     3      3
1325  2012      8     8     8      8
      2010      6     6     6      6
1322  2012     13    13    13     13
      2011      3     3     3      3
      2010     19    19    19     19
1321  2012     15    15    15     15
      2010      5     5     5      5
      2013      4     4     4      4
      2009     13    13    13     13

In [65]:
df[df.part==7].count()

index    1373
make     1373
model    1373
year     1373
part     1373
image    1373
dtype: int64